#!/bin/bash

set -eu

# Set up celery daemon service

echo "Setting up celery daemon service"

sudo cp "$PWD"/celery/celeryworker.service /etc/systemd/system/
sudo cp "$PWD"/celery/celerybeat.service /etc/systemd/system/

systemctl daemon-reload

systemctl enable celeryworker.service
systemctl enable celerybeat.service

