#!/bin/bash

set -eu

# Setup the environment for celery daemon

sudo groupadd celery -f
sudo useradd -g celery celery || echo "User celery already exists"

echo "Creating directories for celery daemon"
sudo mkdir "/etc/conf.d" -p
sudo mkdir "/var/log/celery" -p
sudo mkdir "/var/run/celery" -p

sudo cp "$PWD"/celery/celery.conf /etc/conf.d/celery.conf

sudo chown -R celery:celery /var/log/celery/
sudo chown -R celery:celery /var/run/celery/

echo " celery daemon setup complete."