#!/bin/bash

set -eu

echo "Start gunicorn daemon setup"

sudo adduser ubuntu www-data
sudo adduser www-data ubuntu

sudo mkdir /run/gunicorn -p
sudo chown ubuntu:www-data /run/gunicorn

SOCKET_FILE="/run/gunicorn/gunicorn.sock"

if [ -f $SOCKET_FILE ]
then
  sudo chown ubuntu:www-data  $SOCKET_FILE
fi

echo "Gunicorn daemon setup complete"
