
# https://starship.rs/config/

[nodejs]
version_format = 'node v${raw}'

[python]
# disabled = true
pyenv_version_name = false
detect_folders = ['venv']

[time]
disabled = false
use_12hr = true

[sudo]
disabled = false


[env_var.SERVER_NAME]
default = ''
style = 'bold underline yellow'
format = "| [$env_value]($style) "

[env_var.APP_ALIAS]
default = ''
style = 'blue'
format = "for [$env_value]($style) | "
